
- name: add nginx repository
  copy:
     src: nginx.repo
     dest: /etc/yum.repos.d

- name: install nginx
  yum:
     name: nginx
     state: present

- name: nginx start and enabled
  systemd:
     name: nginx
     state: started
     daemon_reload: yes
     enabled: yes


